"""New Lecture model

Revision ID: baa65987764b
Revises: 099ea13b0517
Create Date: 2019-09-07 12:39:08.805797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baa65987764b'
down_revision = '099ea13b0517'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lecture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('path', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lecture_name'), 'lecture', ['name'], unique=False)
    op.drop_index('ix_activity_name', table_name='activity')
    op.drop_table('activity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=140), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_activity_name', 'activity', ['name'], unique=False)
    op.drop_index(op.f('ix_lecture_name'), table_name='lecture')
    op.drop_table('lecture')
    # ### end Alembic commands ###
